/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ShipBuilderImport } from './routes/ship-builder'
import { Route as EnhancedImport } from './routes/enhanced'
import { Route as AsteroidsImport } from './routes/asteroids'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ShipBuilderRoute = ShipBuilderImport.update({
  id: '/ship-builder',
  path: '/ship-builder',
  getParentRoute: () => rootRoute,
} as any)

const EnhancedRoute = EnhancedImport.update({
  id: '/enhanced',
  path: '/enhanced',
  getParentRoute: () => rootRoute,
} as any)

const AsteroidsRoute = AsteroidsImport.update({
  id: '/asteroids',
  path: '/asteroids',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/asteroids': {
      id: '/asteroids'
      path: '/asteroids'
      fullPath: '/asteroids'
      preLoaderRoute: typeof AsteroidsImport
      parentRoute: typeof rootRoute
    }
    '/enhanced': {
      id: '/enhanced'
      path: '/enhanced'
      fullPath: '/enhanced'
      preLoaderRoute: typeof EnhancedImport
      parentRoute: typeof rootRoute
    }
    '/ship-builder': {
      id: '/ship-builder'
      path: '/ship-builder'
      fullPath: '/ship-builder'
      preLoaderRoute: typeof ShipBuilderImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/asteroids': typeof AsteroidsRoute
  '/enhanced': typeof EnhancedRoute
  '/ship-builder': typeof ShipBuilderRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/asteroids': typeof AsteroidsRoute
  '/enhanced': typeof EnhancedRoute
  '/ship-builder': typeof ShipBuilderRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/asteroids': typeof AsteroidsRoute
  '/enhanced': typeof EnhancedRoute
  '/ship-builder': typeof ShipBuilderRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/asteroids' | '/enhanced' | '/ship-builder'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/asteroids' | '/enhanced' | '/ship-builder'
  id: '__root__' | '/' | '/asteroids' | '/enhanced' | '/ship-builder'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AsteroidsRoute: typeof AsteroidsRoute
  EnhancedRoute: typeof EnhancedRoute
  ShipBuilderRoute: typeof ShipBuilderRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AsteroidsRoute: AsteroidsRoute,
  EnhancedRoute: EnhancedRoute,
  ShipBuilderRoute: ShipBuilderRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/asteroids",
        "/enhanced",
        "/ship-builder"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/asteroids": {
      "filePath": "asteroids.tsx"
    },
    "/enhanced": {
      "filePath": "enhanced.tsx"
    },
    "/ship-builder": {
      "filePath": "ship-builder.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
